export const AUTH_START = "LOGIN_START";
export const AUTH_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_FAIL = "LOGIN_FAIL";

export const REGISTER_START = "LREGISTER_START";
export const REGISTER_SUCCESS = "LREGISTER_SUCCESS";
export const REGISTER_FAIL = "LREGISTER_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_STATE_CHANGE = "AUTH_STATE_CHANGE";

export const FETCH_GAMES_START = "FETCH_GAMES_START";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAIL = "FETCH_GAMES_FAIL";

export const FETCH_THUMBNAILS_SUCCESS = "FETCH_THUMBNAILS_SUCCESS";