export const AUTH_START = "LOGIN_START";
export const AUTH_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_FAIL = "LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_STATE_CHANGE = "AUTH_STATE_CHANGE";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const FETCH_GAMES_START = "FETCH_GAMES_START";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAIL = "FETCH_GAMES_FAIL";
export const FETCH_THUMBNAILS_SUCCESS = "FETCH_THUMBNAILS_SUCCESS";

export const FILTER_GAMES = "FILTER_GAMES";
export const ORDER_GAMES = "ORDER_GAMES";

export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";

export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";

export const SHOW_MOBILE_SIDEBAR = "SHOW_MOBILE_SIDEBAR";

export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAIL = "FETCH_ROOMS_FAIL";
export const FILTER_ROOMS = "FILTER_ROOMS";